primary_region = 'iad'

[build]
dockerfile = "./apps/browser-proxy/Dockerfile"

[[services]]
internal_port = 5432
protocol = "tcp"
[[services.ports]]
handlers = ["proxy_proto"]
port = 5432

[[services]]
internal_port = 443
protocol = "tcp"
[[services.ports]]
port = 443

[[restart]]
policy = "always"
retries = 10

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
