services:
  proxy:
    image: proxy
    build:
      context: ../..
      dockerfile: apps/proxy/Dockerfile
    env_file:
      - .env
    ports:
      - 5432:5432
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN

  tls-init:
    image: tls-init
    build:
      context: ../..
      dockerfile: apps/proxy/Dockerfile
    env_file:
      - .env
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    command: ./proxy/scripts/generate-certs.sh

  dns:
    build:
      context: ./tools/dns
    environment:
      WILDCARD_DOMAIN: db.example.com
      SERVICE_NAME: proxy
    networks:
      default:
        ipv4_address: 173.20.0.10
  psql:
    image: postgres:16
    depends_on:
      - dns
    dns:
      - 173.20.0.10

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 173.20.0.0/24
